from _typeshed import Incomplete

class WarrantException(Exception): ...
class ForceChangePasswordException(WarrantException): ...
class TokenVerificationException(WarrantException): ...

class MFAChallengeException(WarrantException):
    message: Incomplete
    def __init__(self, message, tokens, *args, **kwargs) -> None: ...
    def get_tokens(self): ...

class SoftwareTokenMFAChallengeException(MFAChallengeException): ...
class SMSMFAChallengeException(MFAChallengeException): ...
